#[cfg(test)]
mod command_contract;
mod menu;
mod orchestrator_host;
// Compiled only where the bindings export runs (debug builds and the export test);
// a release build has no export path and would flag every helper as dead.
#[cfg(any(debug_assertions, test))]
mod specta_export;
mod transport;
mod window_host;

use tauri::Manager;

use transport::macros::collect_transport;

use orchestrator_host::OrchestratorState;

/// Builds a tauri-specta Builder over the commands that support `specta::Type`.
///
// Header prepended to the generated tauri_bindings.gen.ts so its provenance is unmistakable.
#[cfg(any(debug_assertions, test))]
pub(crate) const GEN_HEADER: &str =
    "// AUTO-GENERATED by tauri-specta from the Rust IPC layer -- DO NOT MODIFY.\n\
     // Regenerate via the desktop build or the command_contract export test; drift is gated in CI.\n";

pub(crate) fn specta_builder() -> tauri_specta::Builder<tauri::Wry> {
    tauri_specta::Builder::<tauri::Wry>::new()
        .dangerously_cast_bigints_to_number()
        .commands(tauri_specta::collect_commands![
            orchestrator_host::orchestrator_status,
            orchestrator_host::service_health,
            window_host::window_open::<tauri::Wry>,
            window_host::window_focus::<tauri::Wry>,
            window_host::window_close::<tauri::Wry>,
            menu::command_center_set_leader,
            transport::surface::surface_resolve_or_spawn,
            transport::surface::surface_channel::<tauri::Wry>,
            transport::surface::surface_channel_send,
            transport::surface::surface_channel_close,
            transport::surface::surface_spawn,
            transport::surface::surface_close,
            transport::surface::surface_detach,
            transport::logs::log_channel::<tauri::Wry>,
            transport::logs::log_channel_close,
            transport::logs::logs_changed_channel::<tauri::Wry>,
            transport::logs::logs_changed_channel_close,
            transport::notification::notification_channel::<tauri::Wry>,
            transport::notification::notification_channel_close,
            transport::settings::setting_get,
            transport::settings::setting_set,
            transport::settings::setting_list,
            transport::settings::setting_reset,
            transport::settings::setting_resolve,
            transport::settings::settings_resolve,
            transport::notification::notifications_list,
            transport::project::project_create,
            transport::project::project_list,
            transport::project::project_rename,
            transport::project::project_archive,
            transport::project::project_delete,
            transport::project::project_reorder,
            transport::project::project_move,
            transport::project::project_get,
            transport::project::project_search,
            transport::project::project_restore,
            transport::project::project_duplicate,
            transport::project::project_pin,
            transport::project::project_unpin,
            transport::project::project_stop_surfaces,
            transport::workspace::workspace_create,
            transport::workspace::workspace_list,
            transport::workspace::workspace_activity,
            transport::workspace::workspace_rename,
            transport::workspace::workspace_reorder,
            transport::workspace::workspace_delete,
            transport::workspace::workspace_get,
            transport::workspace::workspace_archive,
            transport::workspace::workspace_restore,
            transport::workspace::workspace_pin,
            transport::workspace::workspace_unpin,
            transport::workspace::workspace_stop_surfaces,
            transport::surface::surface_get,
            transport::surface::surface_list_by_session,
            transport::surface::surface_list_resumable,
            transport::surface::surface_find_by_placement,
            transport::surface::surface_stop,
            transport::surface::surface_reconcile,
            transport::session::session_list,
            transport::session::session_create,
            transport::session::session_rename,
            transport::session::session_archive,
            transport::session::session_delete,
            transport::session::session_reorder,
            transport::session::session_layout_set,
            transport::session::session_layout_get,
            transport::session::session_get,
            transport::session::session_list_all,
            transport::session::session_get_launch_spec,
            transport::session::session_search,
            transport::session::session_launch,
            transport::session::session_apply_launch_spec,
            transport::session::session_move,
            transport::session::session_duplicate,
            transport::session::session_pin,
            transport::session::session_unpin,
            transport::session::session_restore,
            transport::session::session_stop_surfaces,
            transport::command::command_list,
            transport::command::command_create,
            transport::command::command_get,
            transport::command::command_delete,
            transport::command::command_rename,
            transport::command::command_edit,
            transport::command::command_pin,
            transport::command::command_unpin,
            transport::command::command_duplicate,
            transport::command::command_seed,
            transport::settings::profile_get_active,
            transport::settings::profile_list,
            transport::settings::profile_create,
            transport::settings::profile_activate,
            transport::settings::profile_rename,
            transport::settings::profile_duplicate,
            transport::settings::profile_discard,
            transport::settings::profile_export,
            transport::settings::profile_import,
            transport::settings::theme_get_active,
            transport::settings::theme_list,
            transport::settings::theme_activate,
            transport::settings::theme_discard,
            transport::settings::theme_export,
            transport::settings::theme_import,
            transport::settings::keybinding_list,
            transport::settings::keybinding_rebind,
            transport::settings::keybinding_reset,
            transport::settings::keybinding_reset_all,
            transport::settings::keybinding_resolve,
            transport::settings::config_reload,
            transport::notification::notification_list_unread,
            transport::notification::notification_count_unread,
            transport::notification::notification_mark_read,
            transport::notification::notification_mark_all_read,
            transport::notification::notification_disregard,
            transport::notification::notification_disregard_all,
            transport::notification::notification_snooze,
            transport::notification::notification_prune,
            transport::template::launch_template_create,
            transport::template::launch_template_list,
            transport::template::launch_template_get,
            transport::template::launch_template_discard,
            transport::template::launch_template_apply_spec,
            transport::template::template_list,
            transport::template::template_get,
            transport::template::template_import,
            transport::template::template_export,
            transport::template::template_discard,
            transport::template::template_pin,
            transport::template::template_unpin,
            transport::logs::log_list,
            transport::logs::log_tail,
        ])
        .events(tauri_specta::collect_events![
            orchestrator_host::StatusWire,
            menu::MenuNavigate,
            menu::CommandCenterOpen,
        ])
}

/// The app's real `Context` (config, embedded frontend, resolved ACL). `generate_context!` may
/// expand only once per binary, so this single call is shared by `run()` and the command-contract
/// test -- the test needs the real ACL (the bundled `default.json`) to drive commands through the
/// live IPC path, which a `mock_context` (empty ACL) cannot do.
fn app_context<R: tauri::Runtime>() -> tauri::Context<R> {
    tauri::generate_context!()
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let dir = tillerd_paths::runtime_dir();
    let (_guard, root) = tillerd_paths::logging::init_file_tracing(
        "tillerd-desktop",
        env!("CARGO_PKG_VERSION"),
        &dir,
    );
    let _root = root.entered();

    let builder = tauri::Builder::default();
    #[cfg(feature = "webdriver")]
    let builder = builder.plugin(tauri_plugin_webdriver::init());
    // Save/restore window size, position, and maximized state across relaunch. The default
    // builder auto-saves on exit and restores on launch; no manual save/restore calls needed.
    #[cfg(desktop)]
    let builder = builder.plugin(tauri_plugin_window_state::Builder::default().build());
    // Native OS notification banners for background (unfocused) events (roadmap 0.0.10).
    let builder = builder.plugin(tauri_plugin_notification::init());
    #[cfg(debug_assertions)]
    specta_builder()
        .export(
            specta_export::ObjectParamTs(
                specta_typescript::Typescript::default().header(GEN_HEADER),
            ),
            concat!(
                env!("CARGO_MANIFEST_DIR"),
                "/../../../packages/client-bindings/src/tauri_bindings.gen.ts"
            ),
        )
        .expect("failed to export tauri bindings");

    builder
        .manage(OrchestratorState::default())
        .manage(menu::LeaderMenuState::default())
        .setup(|app| {
            specta_builder().mount_events(app);

            // Native menu: the platform default (app / Edit / View / Window / Help) with Logs and
            // Command Center entries in the View submenu. Logs routes the renderer to /logs; the
            // Command Center accelerator is the leader key (fires over terminal focus) and emits
            // "command-center:open".
            menu::install_menu(app)?;

            // Construct and boot the single embedded orchestrator instance; it
            // streams lifecycle events to the renderer and reaches `ready`.
            let handle = app.handle().clone();
            let state = app.state::<OrchestratorState>();
            orchestrator_host::spawn_boot(handle.clone(), state.inner());
            orchestrator_host::spawn_logs_watcher(handle);
            Ok(())
        })
        .invoke_handler(collect_transport!())
        .build(app_context())
        .expect("error while building tauri application")
        .run(|_app_handle, _event| {});
}
