mod bridge;
#[cfg(test)]
mod command_contract;
mod daemon_session;
mod diag;
mod gate_admin;
mod menu;
mod notification_host;
mod orchestrator_host;
mod specta_export;
mod store;
mod supervisor;
mod surface_host;
mod transport;
mod window_host;

use tauri::Manager;

use transport::macros::collect_transport;

use bridge::BridgeState;
use orchestrator_host::OrchestratorState;
use store::StoreState;
use supervisor::SupervisorState;

/// Builds a tauri-specta Builder over the commands that support `specta::Type`.
///
/// Excluded from the specta set (still registered in the tauri handler via
/// `collect_transport!`):
/// - `daemon_connect` -- concrete `AppHandle<Wry>` + `ipc::Channel`; not generic
// Header prepended to the generated tauri_bindings.gen.ts so its provenance is unmistakable.
pub(crate) const GEN_HEADER: &str =
    "// AUTO-GENERATED by tauri-specta from the Rust IPC layer -- DO NOT MODIFY.\n\
     // Regenerate via the desktop build or the command_contract export test; drift is gated in CI.\n";

pub(crate) fn specta_builder() -> tauri_specta::Builder<tauri::Wry> {
    tauri_specta::Builder::<tauri::Wry>::new()
        .dangerously_cast_bigints_to_number()
        .commands(tauri_specta::collect_commands![
            bridge::daemon_send,
            bridge::daemon_disconnect,
            store::registry_get,
            store::registry_set,
            store::registry_remove,
            store::registry_list,
            supervisor::daemon_ensure,
            orchestrator_host::orchestrator_status,
            orchestrator_host::service_health,
            window_host::window_open::<tauri::Wry>,
            window_host::window_focus::<tauri::Wry>,
            window_host::window_close::<tauri::Wry>,
            menu::command_center_set_leader,
            surface_host::surface_channel::<tauri::Wry>,
            surface_host::surface_channel_send_cmd,
            surface_host::surface_spawn,
            surface_host::surface_close,
            surface_host::surface_detach,
            transport::domain::setting_get,
            transport::domain::setting_set,
            transport::domain::setting_list,
            transport::domain::setting_reset,
            transport::domain::setting_resolve,
            transport::domain::settings_resolve,
            transport::domain::notifications_list,
            transport::domain::project_create,
            transport::domain::project_list,
            transport::domain::project_rename,
            transport::domain::project_archive,
            transport::domain::project_delete,
            transport::domain::project_reorder,
            transport::domain::project_move,
            transport::domain::project_get,
            transport::domain::project_search,
            transport::domain::project_restore,
            transport::domain::project_duplicate,
            transport::domain::project_pin,
            transport::domain::project_unpin,
            transport::domain::project_stop_surfaces,
            transport::domain::workspace_create,
            transport::domain::workspace_list,
            transport::domain::workspace_rename,
            transport::domain::workspace_reorder,
            transport::domain::workspace_delete,
            transport::domain::workspace_get,
            transport::domain::workspace_archive,
            transport::domain::workspace_restore,
            transport::domain::workspace_pin,
            transport::domain::workspace_unpin,
            transport::domain::workspace_stop_surfaces,
            transport::domain::surface_get,
            transport::domain::surface_list_by_session,
            transport::domain::surface_list_resumable,
            transport::domain::surface_find_by_placement,
            transport::domain::surface_stop,
            transport::domain::surface_reconcile,
            transport::domain::session_list,
            transport::domain::session_create,
            transport::domain::session_rename,
            transport::domain::session_archive,
            transport::domain::session_delete,
            transport::domain::session_reorder,
            transport::domain::session_layout_set,
            transport::domain::session_layout_get,
            transport::domain::session_get,
            transport::domain::session_list_all,
            transport::domain::session_get_launch_spec,
            transport::domain::session_search,
            transport::domain::session_launch,
            transport::domain::session_apply_launch_spec,
            transport::domain::session_move,
            transport::domain::session_duplicate,
            transport::domain::session_pin,
            transport::domain::session_unpin,
            transport::domain::session_restore,
            transport::domain::session_stop_surfaces,
            transport::domain::command_list,
            transport::domain::command_create,
            transport::domain::command_get,
            transport::domain::command_delete,
            transport::domain::command_rename,
            transport::domain::command_edit,
            transport::domain::command_pin,
            transport::domain::command_unpin,
            transport::domain::command_duplicate,
            transport::domain::command_seed,
            transport::domain::profile_get_active,
            transport::domain::profile_list,
            transport::domain::profile_create,
            transport::domain::profile_activate,
            transport::domain::profile_rename,
            transport::domain::profile_duplicate,
            transport::domain::profile_discard,
            transport::domain::profile_export,
            transport::domain::profile_import,
            transport::domain::theme_get_active,
            transport::domain::theme_list,
            transport::domain::theme_activate,
            transport::domain::theme_discard,
            transport::domain::theme_export,
            transport::domain::theme_import,
            transport::domain::keybinding_list,
            transport::domain::keybinding_rebind,
            transport::domain::keybinding_reset,
            transport::domain::keybinding_reset_all,
            transport::domain::keybinding_resolve,
            transport::domain::config_reload,
            transport::domain::notification_list_unread,
            transport::domain::notification_count_unread,
            transport::domain::notification_mark_read,
            transport::domain::notification_mark_all_read,
            transport::domain::notification_disregard,
            transport::domain::notification_disregard_all,
            transport::domain::notification_snooze,
            transport::domain::notification_prune,
            transport::domain::launch_template_create,
            transport::domain::launch_template_list,
            transport::domain::launch_template_get,
            transport::domain::launch_template_discard,
            transport::domain::launch_template_apply_spec,
            transport::domain::template_list,
            transport::domain::template_get,
            transport::domain::template_import,
            transport::domain::template_export,
            transport::domain::template_discard,
            transport::domain::template_pin,
            transport::domain::template_unpin,
            transport::domain::log_list,
            transport::domain::log_tail,
        ])
        .events(tauri_specta::collect_events![
            orchestrator_host::StatusWire,
            orchestrator_host::LogsChanged,
            notification_host::NotificationWire,
            transport::sink::SurfaceStatusPayload,
            transport::sink::SurfaceExitPayload,
            transport::sink::SurfaceErrorPayload,
            bridge::DaemonLost,
            menu::MenuNavigate,
            menu::CommandCenterOpen,
        ])
}

/// The app's real `Context` (config, embedded frontend, resolved ACL). `generate_context!` may
/// expand only once per binary, so this single call is shared by `run()` and the command-contract
/// test -- the test needs the real ACL (the bundled `default.json`) to drive commands through the
/// live IPC path, which a `mock_context` (empty ACL) cannot do.
fn app_context<R: tauri::Runtime>() -> tauri::Context<R> {
    tauri::generate_context!()
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let dir = tillerd_paths::runtime_dir();
    let (_guard, root) = tillerd_paths::logging::init_file_tracing(
        "tillerd-desktop",
        env!("CARGO_PKG_VERSION"),
        &dir,
    );
    let _root = root.entered();

    let builder = tauri::Builder::default();
    #[cfg(feature = "webdriver")]
    let builder = builder.plugin(tauri_plugin_webdriver::init());
    // Save/restore window size, position, and maximized state across relaunch. The default
    // builder auto-saves on exit and restores on launch; no manual save/restore calls needed.
    #[cfg(desktop)]
    let builder = builder.plugin(tauri_plugin_window_state::Builder::default().build());
    // Native OS notification banners for background (unfocused) events (roadmap 0.0.10).
    let builder = builder.plugin(tauri_plugin_notification::init());
    #[cfg(debug_assertions)]
    specta_builder()
        .export(
            specta_export::ObjectParamTs(
                specta_typescript::Typescript::default().header(GEN_HEADER),
            ),
            concat!(
                env!("CARGO_MANIFEST_DIR"),
                "/../../../packages/client-bindings/src/tauri_bindings.gen.ts"
            ),
        )
        .expect("failed to export tauri bindings");

    builder
        .manage(BridgeState::default())
        .manage(StoreState::load())
        .manage(SupervisorState::default())
        .manage(OrchestratorState::default())
        .manage(menu::LeaderMenuState::default())
        .setup(|app| {
            specta_builder().mount_events(app);

            // Native menu: the platform default (app / Edit / View / Window / Help) with Logs and
            // Command Center entries in the View submenu. Logs routes the renderer to /logs; the
            // Command Center accelerator is the leader key (fires over terminal focus) and emits
            // "command-center:open".
            menu::install_menu(app)?;

            // Construct and boot the single embedded orchestrator instance; it
            // streams lifecycle events to the renderer and reaches `ready`.
            let handle = app.handle().clone();
            let state = app.state::<OrchestratorState>();
            orchestrator_host::spawn_boot(handle.clone(), state.inner());
            orchestrator_host::spawn_logs_watcher(handle);
            Ok(())
        })
        .invoke_handler(collect_transport!(bridge::daemon_connect))
        .build(app_context())
        .expect("error while building tauri application")
        .run(|app_handle, event| {
            // Shutdown is bound to app exit (ExitRequested fires only when the LAST window closes),
            // never per-window-close -- so closing a parent window while a detached child remains
            // open leaves the owned daemon running (roadmap 0.0.11, desktop-shell spec).
            if let tauri::RunEvent::ExitRequested { .. } = event {
                supervisor::shutdown_owned(&app_handle.state::<SupervisorState>());
            }
        });
}
