// AUTO-GENERATED by tauri-specta from the Rust IPC layer -- DO NOT MODIFY.
// Regenerate via the desktop build or the command_contract export test; drift is gated in CI.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	daemonSend: (args: { bytes: number[] }) => typedError<null, string>(__TAURI_INVOKE("daemon_send", args)),
	daemonDisconnect: () => typedError<null, string>(__TAURI_INVOKE("daemon_disconnect")),
	/**  Byte length, or `None` (JS `null`) when the file is absent -- distinct from an empty file (0). */
	fileSize: (args: { path: string }) => __TAURI_INVOKE<number | null>("file_size", args),
	/**
	 *  List the structured `.log` files under the runtime logs directory, sorted by
	 *  name. Each entry carries the absolute path the renderer reads through
	 *  `file_read` / `file_size`. Empty when the logs directory is absent.
	 */
	listLogFiles: () => __TAURI_INVOKE<LogFileEntry[]>("list_log_files"),
	registryGet: (args: { sessionId: string }) => typedError<string | null, null>(__TAURI_INVOKE("registry_get", args)),
	registrySet: (args: { sessionId: string; cwd: string }) => typedError<null, null>(__TAURI_INVOKE("registry_set", args)),
	registryRemove: (args: { sessionId: string }) => typedError<null, null>(__TAURI_INVOKE("registry_remove", args)),
	registryList: () => typedError<RegistryEntry[], null>(__TAURI_INVOKE("registry_list")),
	/**  Adopt a live daemon recorded in the manifest, else spawn one and wait for reachability. */
	daemonEnsure: () => typedError<EnsureResult, string>(__TAURI_INVOKE("daemon_ensure")),
	orchestratorStatus: () => __TAURI_INVOKE<StatusWire>("orchestrator_status"),
	serviceHealth: () => __TAURI_INVOKE<ServiceHealthWire[]>("service_health"),
	windowOpen: (args: { label: string; query: string }) => typedError<null, string>(__TAURI_INVOKE("window_open", args)),
	windowFocus: (args: { label: string }) => typedError<null, string>(__TAURI_INVOKE("window_focus", args)),
	windowClose: (args: { label: string }) => typedError<null, string>(__TAURI_INVOKE("window_close", args)),
	/**  Rebind the native leader accelerator. No-op until the leader item is installed. */
	commandCenterSetLeader: (args: { accelerator: string }) => typedError<null, string>(__TAURI_INVOKE("command_center_set_leader", args)),
	/**
	 *  Create (or revisit) a surface at a session + placement. On revisit, the existing
	 *  surface's output channel is re-registered and its proxy re-attached (replaying
	 *  scrollback); otherwise a fresh surface is spawned. Returns the surface id.
	 */
	surfaceCreate: (args: { channel: Channel<number[]>; sessionId: string; placement: string; cols: number; rows: number; cwd: string | null }) => typedError<string, string>(__TAURI_INVOKE("surface_create", args)),
	/**  Spawn a surface in a session with a minted placement. Returns the surface id. */
	surfaceSpawn: (args: { sessionId: string }) => typedError<string, string>(__TAURI_INVOKE("surface_spawn", args)),
	/**
	 *  Close the surface bound to a session + placement: drop its output channel and
	 *  remove its runtime proxy + record.
	 */
	surfaceClose: (args: { sessionId: string; placement: string }) => typedError<null, string>(__TAURI_INVOKE("surface_close", args)),
	/**  Send raw input bytes to a surface's PTY. Off the bus; the payload is never logged. */
	surfaceInput: (args: { surfaceId: string; bytes: number[] }) => typedError<null, string>(__TAURI_INVOKE("surface_input", args)),
	/**  Resize a surface's PTY. Off the bus (high-frequency pass-through). */
	surfaceResize: (args: { surfaceId: string; cols: number; rows: number }) => typedError<null, string>(__TAURI_INVOKE("surface_resize", args)),
	/**
	 *  Detach a surface's proxy stream; the PTY keeps running in the daemon. Drops the
	 *  output channel so the stream goes quiet.
	 */
	surfaceDetach: (args: { surfaceId: string }) => typedError<null, string>(__TAURI_INVOKE("surface_detach", args)),
	settingList: (args: { scope: string; projectId: string | null }) => typedError<SettingView[], string>(__TAURI_INVOKE("setting_list", args)),
	/**
	 *  Clear a setting override at a scope (revert to inherited/default).
	 *  `scope` is `"global"` or `"project"`; `project_id` is required for the project scope.
	 */
	settingReset: (args: { scope: string; projectId: string | null; key: string }) => typedError<null, string>(__TAURI_INVOKE("setting_reset", args)),
	/**
	 *  Effective value for a project: project override if set, else global, else `None`.
	 *  Returns the raw JSON-encoded string (not parsed), matching the bus output.
	 */
	settingResolve: (args: { projectId: string; key: string }) => typedError<string | null, string>(__TAURI_INVOKE("setting_resolve", args)),
	/**
	 *  Full effective settings map for a project (global merged with project overrides).
	 *  Values in each `SettingView` are parsed back to JSON.
	 */
	settingsResolve: (args: { projectId: string }) => typedError<SettingView[], string>(__TAURI_INVOKE("settings_resolve", args)),
	/**  Durable notification history (most recent first) for the renderer to hydrate on boot. */
	notificationsList: () => typedError<NotificationWire[], string>(__TAURI_INVOKE("notifications_list")),
	projectCreate: (args: { name: string | null; workspaceId: string | null }) => typedError<ProjectView, string>(__TAURI_INVOKE("project_create", args)),
	projectList: (args: { workspaceId: string | null }) => typedError<ProjectView[], string>(__TAURI_INVOKE("project_list", args)),
	projectRename: (args: { id: string; name: string }) => typedError<null, string>(__TAURI_INVOKE("project_rename", args)),
	projectArchive: (args: { id: string }) => typedError<null, string>(__TAURI_INVOKE("project_archive", args)),
	projectDelete: (args: { id: string }) => typedError<null, string>(__TAURI_INVOKE("project_delete", args)),
	projectReorder: (args: { id: string; sortOrder: number }) => typedError<null, string>(__TAURI_INVOKE("project_reorder", args)),
	projectMove: (args: { id: string; workspaceId: string }) => typedError<null, string>(__TAURI_INVOKE("project_move", args)),
	projectGet: (args: { id: string }) => typedError<{
	id: string,
	name: string,
	sourceKind: string,
	rootPath: string | null,
	workspaceId: string,
} | null, string>(__TAURI_INVOKE("project_get", args)),
	projectSearch: (args: { workspaceId: string; query: string; limit: number }) => typedError<ProjectView[], string>(__TAURI_INVOKE("project_search", args)),
	projectRestore: (args: { id: string }) => typedError<null, string>(__TAURI_INVOKE("project_restore", args)),
	projectDuplicate: (args: { sourceId: string; name: string | null }) => typedError<null, string>(__TAURI_INVOKE("project_duplicate", args)),
	projectPin: (args: { id: string }) => typedError<null, string>(__TAURI_INVOKE("project_pin", args)),
	projectUnpin: (args: { id: string }) => typedError<null, string>(__TAURI_INVOKE("project_unpin", args)),
	projectStopSurfaces: (args: { id: string }) => typedError<null, string>(__TAURI_INVOKE("project_stop_surfaces", args)),
	workspaceCreate: (args: { name: string }) => typedError<WorkspaceView, string>(__TAURI_INVOKE("workspace_create", args)),
	workspaceList: () => typedError<WorkspaceView[], string>(__TAURI_INVOKE("workspace_list")),
	workspaceRename: (args: { id: string; name: string }) => typedError<null, string>(__TAURI_INVOKE("workspace_rename", args)),
	workspaceReorder: (args: { id: string; sortOrder: number }) => typedError<null, string>(__TAURI_INVOKE("workspace_reorder", args)),
	workspaceDelete: (args: { id: string }) => typedError<null, string>(__TAURI_INVOKE("workspace_delete", args)),
	workspaceGet: (args: { id: string }) => typedError<{
	id: string,
	name: string,
} | null, string>(__TAURI_INVOKE("workspace_get", args)),
	workspaceArchive: (args: { id: string }) => typedError<null, string>(__TAURI_INVOKE("workspace_archive", args)),
	workspaceRestore: (args: { id: string }) => typedError<null, string>(__TAURI_INVOKE("workspace_restore", args)),
	workspacePin: (args: { id: string }) => typedError<null, string>(__TAURI_INVOKE("workspace_pin", args)),
	workspaceUnpin: (args: { id: string }) => typedError<null, string>(__TAURI_INVOKE("workspace_unpin", args)),
	workspaceStopSurfaces: (args: { id: string }) => typedError<null, string>(__TAURI_INVOKE("workspace_stop_surfaces", args)),
	surfaceGet: (args: { id: string }) => typedError<{
	id: string,
	sessionId: string,
	kind: string,
	cwd: string | null,
	status: string,
	placement: string | null,
} | null, string>(__TAURI_INVOKE("surface_get", args)),
	surfaceListBySession: (args: { session: string; limit: number | null; offset: number | null; after: string | null }) => typedError<SurfaceView[], string>(__TAURI_INVOKE("surface_list_by_session", args)),
	surfaceListResumable: () => typedError<SurfaceView[], string>(__TAURI_INVOKE("surface_list_resumable")),
	surfaceFindByPlacement: (args: { session: string; placement: string }) => typedError<{
	id: string,
	sessionId: string,
	kind: string,
	cwd: string | null,
	status: string,
	placement: string | null,
} | null, string>(__TAURI_INVOKE("surface_find_by_placement", args)),
	surfaceStop: (args: { id: string }) => typedError<null, string>(__TAURI_INVOKE("surface_stop", args)),
	surfaceReconcile: () => typedError<null, string>(__TAURI_INVOKE("surface_reconcile")),
	sessionList: (args: { projectId: string | null; limit: number | null; offset: number | null }) => typedError<SessionView[], string>(__TAURI_INVOKE("session_list", args)),
	/**
	 *  Create a session, bring its launch spec to life. The `LaunchSession` tail is
	 *  non-fatal (a spec-less session is valid), so this stays hand-written rather than
	 *  using `transport_create!`.
	 */
	sessionCreate: (args: { projectId: string | null; title: string | null; titleSource: string | null; templateId: string | null }) => typedError<SessionView, string>(__TAURI_INVOKE("session_create", args)),
	sessionRename: (args: { id: string; title: string }) => typedError<null, string>(__TAURI_INVOKE("session_rename", args)),
	sessionArchive: (args: { id: string }) => typedError<null, string>(__TAURI_INVOKE("session_archive", args)),
	sessionDelete: (args: { id: string }) => typedError<null, string>(__TAURI_INVOKE("session_delete", args)),
	sessionReorder: (args: { id: string; sortOrder: number }) => typedError<null, string>(__TAURI_INVOKE("session_reorder", args)),
	sessionLayoutSet: (args: { id: string; layoutJson: string }) => typedError<null, string>(__TAURI_INVOKE("session_layout_set", args)),
	sessionLayoutGet: (args: { id: string }) => typedError<string | null, string>(__TAURI_INVOKE("session_layout_get", args)),
	sessionGet: (args: { id: string }) => typedError<{
	id: string,
	projectId: string,
	title: string,
	titleSource: string,
	createdAt: string,
} | null, string>(__TAURI_INVOKE("session_get", args)),
	sessionListAll: (args: { limit: number | null; offset: number | null; after: string | null }) => typedError<SessionView[], string>(__TAURI_INVOKE("session_list_all", args)),
	sessionGetLaunchSpec: (args: { id: string }) => typedError<LaunchSpec | null, string>(__TAURI_INVOKE("session_get_launch_spec", args)),
	sessionSearch: (args: { query: string }) => typedError<SessionView[], string>(__TAURI_INVOKE("session_search", args)),
	sessionLaunch: (args: { id: string }) => typedError<null, string>(__TAURI_INVOKE("session_launch", args)),
	sessionApplyLaunchSpec: (args: { id: string; specVersion: number; specJson: string }) => typedError<null, string>(__TAURI_INVOKE("session_apply_launch_spec", args)),
	sessionMove: (args: { id: string; targetProjectId: string }) => typedError<null, string>(__TAURI_INVOKE("session_move", args)),
	sessionDuplicate: (args: { id: string }) => typedError<null, string>(__TAURI_INVOKE("session_duplicate", args)),
	sessionPin: (args: { id: string }) => typedError<null, string>(__TAURI_INVOKE("session_pin", args)),
	sessionUnpin: (args: { id: string }) => typedError<null, string>(__TAURI_INVOKE("session_unpin", args)),
	sessionRestore: (args: { id: string }) => typedError<null, string>(__TAURI_INVOKE("session_restore", args)),
	sessionStopSurfaces: (args: { id: string }) => typedError<null, string>(__TAURI_INVOKE("session_stop_surfaces", args)),
	commandList: () => typedError<CommandView[], string>(__TAURI_INVOKE("command_list")),
	commandCreate: (args: { req: CreateCommandRequest }) => typedError<CommandView, string>(__TAURI_INVOKE("command_create", args)),
	commandGet: (args: { id: string }) => typedError<{
	id: string,
	name: string,
	origin: string,
	cli: string,
	args: string[],
	env: { [key in string]: string },
} | null, string>(__TAURI_INVOKE("command_get", args)),
	commandDelete: (args: { id: string }) => typedError<null, string>(__TAURI_INVOKE("command_delete", args)),
	commandRename: (args: { id: string; name: string }) => typedError<null, string>(__TAURI_INVOKE("command_rename", args)),
	commandEdit: (args: { id: string; cli: string; args: string[]; env: { [key in string]: string } }) => typedError<null, string>(__TAURI_INVOKE("command_edit", args)),
	commandPin: (args: { id: string }) => typedError<null, string>(__TAURI_INVOKE("command_pin", args)),
	commandUnpin: (args: { id: string }) => typedError<null, string>(__TAURI_INVOKE("command_unpin", args)),
	commandDuplicate: (args: { id: string; name: string }) => typedError<null, string>(__TAURI_INVOKE("command_duplicate", args)),
	commandSeed: () => typedError<null, string>(__TAURI_INVOKE("command_seed")),
	profileGetActive: () => typedError<Profile | null, string>(__TAURI_INVOKE("profile_get_active")),
	profileList: () => typedError<ProfileView[], string>(__TAURI_INVOKE("profile_list")),
	/**
	 *  Create a new profile with a caller-supplied id. Hand-written (no GetProfileById
	 *  query): executes NewProfile then reads back via ListProfiles + id filter.
	 */
	profileCreate: (args: { id: string; name: string }) => typedError<ProfileView, string>(__TAURI_INVOKE("profile_create", args)),
	profileActivate: (args: { id: string }) => typedError<null, string>(__TAURI_INVOKE("profile_activate", args)),
	profileRename: (args: { id: string; newName: string }) => typedError<null, string>(__TAURI_INVOKE("profile_rename", args)),
	profileDuplicate: (args: { sourceId: string; newId: string; newName: string }) => typedError<null, string>(__TAURI_INVOKE("profile_duplicate", args)),
	profileDiscard: (args: { id: string }) => typedError<null, string>(__TAURI_INVOKE("profile_discard", args)),
	profileExport: (args: { id: string }) => typedError<number[] | null, string>(__TAURI_INVOKE("profile_export", args)),
	profileImport: (args: { profileJson: string }) => typedError<null, string>(__TAURI_INVOKE("profile_import", args)),
	themeGetActive: () => typedError<Theme | null, string>(__TAURI_INVOKE("theme_get_active")),
	themeList: () => typedError<ThemeView[], string>(__TAURI_INVOKE("theme_list")),
	themeActivate: (args: { id: string }) => typedError<null, string>(__TAURI_INVOKE("theme_activate", args)),
	themeDiscard: (args: { id: string }) => typedError<null, string>(__TAURI_INVOKE("theme_discard", args)),
	themeExport: (args: { id: string }) => typedError<number[] | null, string>(__TAURI_INVOKE("theme_export", args)),
	themeImport: (args: { id: string; name: string; origin: string; dataJson: string | null }) => typedError<null, string>(__TAURI_INVOKE("theme_import", args)),
	keybindingList: (args: { defaultsJson: string }) => typedError<KeybindingView[], string>(__TAURI_INVOKE("keybinding_list", args)),
	keybindingRebind: (args: { action: string; chord: string; defaultsJson: string }) => typedError<null, string>(__TAURI_INVOKE("keybinding_rebind", args)),
	keybindingReset: (args: { action: string; defaultsJson: string }) => typedError<null, string>(__TAURI_INVOKE("keybinding_reset", args)),
	keybindingResetAll: (args: { defaultsJson: string }) => typedError<null, string>(__TAURI_INVOKE("keybinding_reset_all", args)),
	keybindingResolve: (args: { action: string; defaultsJson: string }) => typedError<string | null, string>(__TAURI_INVOKE("keybinding_resolve", args)),
	configReload: () => typedError<null, string>(__TAURI_INVOKE("config_reload")),
	notificationListUnread: (args: { limit: number | null; offset: number | null; after: string | null }) => typedError<Listing<NotificationView>, string>(__TAURI_INVOKE("notification_list_unread", args)),
	notificationCountUnread: () => typedError<number, string>(__TAURI_INVOKE("notification_count_unread")),
	notificationMarkRead: (args: { id: string }) => typedError<null, string>(__TAURI_INVOKE("notification_mark_read", args)),
	notificationMarkAllRead: () => typedError<null, string>(__TAURI_INVOKE("notification_mark_all_read")),
	notificationDisregard: (args: { id: string }) => typedError<null, string>(__TAURI_INVOKE("notification_disregard", args)),
	notificationDisregardAll: () => typedError<null, string>(__TAURI_INVOKE("notification_disregard_all")),
	notificationSnooze: (args: { id: string; snoozeUntil: number | null }) => typedError<null, string>(__TAURI_INVOKE("notification_snooze", args)),
	notificationPrune: (args: { keep: number }) => typedError<null, string>(__TAURI_INVOKE("notification_prune", args)),
	launchTemplateCreate: (args: { projectId: string; specVersion: number; specJson: string }) => typedError<LaunchTemplateView, string>(__TAURI_INVOKE("launch_template_create", args)),
	launchTemplateList: (args: { projectId: string; limit: number | null; offset: number | null; after: string | null }) => typedError<LaunchTemplateView[], string>(__TAURI_INVOKE("launch_template_list", args)),
	launchTemplateGet: (args: { id: string }) => typedError<{
	id: string,
	projectId: string,
	specVersion: number,
	specJson: string,
} | null, string>(__TAURI_INVOKE("launch_template_get", args)),
	launchTemplateDiscard: (args: { id: string }) => typedError<null, string>(__TAURI_INVOKE("launch_template_discard", args)),
	launchTemplateApplySpec: (args: { id: string; specVersion: number; specJson: string }) => typedError<null, string>(__TAURI_INVOKE("launch_template_apply_spec", args)),
	templateList: () => typedError<TemplateView[], string>(__TAURI_INVOKE("template_list")),
	templateGet: (args: { id: string }) => typedError<{
	id: string,
	name: string,
	origin: string,
	pinned: boolean,
	specVersion: number,
	specJson: string,
} | null, string>(__TAURI_INVOKE("template_get", args)),
	templateImport: (args: { name: string; specVersion: number; specJson: string }) => typedError<null, string>(__TAURI_INVOKE("template_import", args)),
	templateExport: (args: { id: string; destPath: string }) => typedError<null, string>(__TAURI_INVOKE("template_export", args)),
	templateDiscard: (args: { id: string }) => typedError<null, string>(__TAURI_INVOKE("template_discard", args)),
	templatePin: (args: { id: string }) => typedError<null, string>(__TAURI_INVOKE("template_pin", args)),
	templateUnpin: (args: { id: string }) => typedError<null, string>(__TAURI_INVOKE("template_unpin", args)),
};

/** Events */
export const events = {
	commandCenterOpen: makeEvent<CommandCenterOpen>("command-center:open"),
	daemonLost: makeEvent<DaemonLost>("daemon-lost"),
	menuNavigate: makeEvent<MenuNavigate>("menu:navigate"),
	notificationEvent: makeEvent<NotificationWire>("notification://event"),
	orchestratorStatus: makeEvent<StatusWire>("orchestrator://status"),
	surfaceExit: makeEvent<SurfaceExitPayload>("surface://exit"),
	surfaceStatus: makeEvent<SurfaceStatusPayload>("surface://status"),
	surfaceError: makeEvent<SurfaceErrorPayload>("surface:error"),
};

/* Types */
export type CommandCenterOpen = string;

export type CommandRef = ({ library_ref: string }) & { args?: never; executable?: never } | ({ executable: string; args: string[] }) & { library_ref?: never };

/**
 *  Flat read model for a command-library row. Serializes to the SDK `Command` wire
 *  shape (the same camelCase JSON the prior `CommandResponse` host struct produced).
 * 
 *  `args`/`env` are stored as JSON text columns (`args_json`/`env_json`); the
 *  `#[sqlx(rename = ..., json)]` decodes them straight into the built-in collections,
 *  mirroring the `Command` entity's `#[sqlx(json)]` fields.
 */
export type CommandView = {
	id: string,
	name: string,
	origin: string,
	cli: string,
	args: string[],
	env: { [key in string]: string },
};

export type CreateCommandRequest = {
	name: string,
	cli: string,
	args?: string[],
	env?: { [key in string]: string },
};

/**  Unit payload for the daemon-lost event (connection dropped unexpectedly). */
export type DaemonLost = null;

export type EnsureResult = {
	ownership: string,
	socket: string,
};

/**  A keybinding entry: action and its effective chord. */
export type KeybindingEntry = {
	action: string,
	chord: string,
};

/**
 *  Read model for a keybinding. Wraps a merged `KeybindingEntry` and serializes
 *  transparently (same `{ action, chord }` JSON the entity produced).
 */
export type KeybindingView = KeybindingEntry;

export type LaunchItem = {
	target: string,
	placement: string | null,
	command: CommandRef,
};

export type LaunchSpec = {
	version: number,
	items: LaunchItem[],
};

/**
 *  Read model for a session's launch spec (the migrated recipe + placements).
 * 
 *  `GetLaunchSpec` deserializes and migrates the stored `spec_json` blob, so this
 *  View is not a flat row map; it wraps the typed spec and serializes identically.
 */
export type LaunchSpecView = LaunchSpec;

/**
 *  Flat read model for a project-bound launch template row.
 * 
 *  Decoded straight from the `launch_template` table via `query_as`.
 */
export type LaunchTemplateView = {
	id: string,
	projectId: string,
	specVersion: number,
	specJson: string,
};

/**  A page of results with an optional continuation cursor for the next page. */
export type Listing<T> = {
	items: T[],
	/**  The cursor for the next page, if more items exist after this page. */
	next: string | null,
};

/**  One structured log file under the runtime logs directory. */
export type LogFileEntry = {
	/**  File name, e.g. `tillerd-daemon.2026-06-13.log`. */
	name: string,
	/**  Absolute path, passed back to `file_read` / `file_size`. */
	path: string,
	/**  Current byte size. */
	size: number,
};

export type MenuNavigate = string;

/**
 *  Flat read model for a notification row. Serializes to the SDK `NotificationEvent`
 *  wire shape -- the same camelCase JSON the host `NotificationWire` produced from a
 *  `NotificationRecord` (internal columns `actions_json`/`read`/`snooze_until` are
 *  not on the wire and so are omitted here).
 * 
 *  Optionals serialize as null (not omitted) so serialize/deserialize stay symmetric and specta
 *  emits a single type rather than _Serialize/_Deserialize variants.
 */
export type NotificationView = {
	id: string,
	category: string,
	severity: string,
	title: string | null,
	message: string,
	detail: string | null,
	ts: number,
	sessionId: string | null,
	surfaceId: string | null,
};

/**  One notification on the wire. Field names match the SDK `NotificationEvent`. */
export type NotificationWire = {
	id: string,
	category: string,
	severity: string,
	title: string | null,
	message: string,
	detail: string | null,
	ts: number,
	sessionId: string | null,
	surfaceId: string | null,
};

/**  A stored profile: id, name, and a map of setting overrides. */
export type Profile = {
	id: string,
	name: string,
	/**  Setting overrides keyed by setting key. Values are JSON-encoded. */
	settings?: { [key in string]: string },
};

/**
 *  Read model for a profile. Wraps the loaded `Profile` and serializes transparently
 *  (same `{ id, name, settings }` JSON the entity produced).
 */
export type ProfileView = Profile;

/**  Flat read model for a project row. Serializes to the SDK `Project` wire shape. */
export type ProjectView = {
	id: string,
	name: string,
	sourceKind: string,
	rootPath: string | null,
	workspaceId: string,
};

export type RegistryEntry = {
	sessionId: string,
	cwd: string,
};

/**  One service's health on the wire. */
export type ServiceHealthWire = {
	name: string,
	version: string | null,
	state: ServiceStateWire,
};

/**
 *  A service's state on the wire. Additive read-only health surface; mirrors
 *  `orchestrator::ServiceState`.
 */
export type ServiceStateWire = "starting" | "ready" | "draining" | "versionMismatch" | "unavailable";

/**
 *  Flat read model for a session row. Serializes to the SDK `Session` wire shape
 *  (the same camelCase JSON the prior `SessionResponse` host struct produced).
 */
export type SessionView = {
	id: string,
	projectId: string,
	title: string,
	titleSource: string,
	createdAt: string,
};

/**
 *  One stored setting at a scope. Serializes to `{ "key": ..., "value": <json> }`,
 *  matching the host's prior `SettingEntryResponse`: the persisted `value_json`
 *  string is parsed back into its JSON value for the wire.
 */
export type SettingView = {
	key: string,
	/**
	 *  Opaque JSON payload; typed as `unknown` in TypeScript to avoid recursive
	 *  expansion of `serde_json::Value` at specta export time.
	 */
	value: unknown,
};

/**  The boot lifecycle status as seen on the wire. Unchanged from the prior host. */
export type StatusWire = { state: "booting" } | { state: "openingStore" } | { state: "supervising" } | { state: "ready" } | { state: "failed"; reason: string };

export type SurfaceErrorPayload = {
	surfaceId: string,
	reason: string,
};

export type SurfaceExitPayload = {
	surfaceId: string,
	qualifier: string,
};

export type SurfaceStatusPayload = {
	surfaceId: string,
	status: string,
};

/**
 *  Flat read model for a surface row. Serializes to the surface wire shape
 *  (camelCase keys) and decodes straight from a row via `query_as`.
 * 
 *  `kind` and `status` are the stored string columns (`terminal`/`diff` and
 *  `pending`/`live`/`idle`/`failed`); the read path needs no enum round-trip.
 */
export type SurfaceView = {
	id: string,
	sessionId: string,
	kind: string,
	cwd: string | null,
	status: string,
	placement: string | null,
};

/**
 *  Flat read model for a portable library template.
 * 
 *  Built from the filesystem template index + bundle (not table-mapped), so it is
 *  assembled by hand in the query handler rather than via `query_as`.
 */
export type TemplateView = {
	id: string,
	name: string,
	origin: string,
	pinned: boolean,
	specVersion: number,
	specJson: string,
};

/**  A stored theme. */
export type Theme = {
	id: string,
	name: string,
	origin: ThemeOrigin,
	/**  Opaque theme data (colors, fonts, etc.) as raw JSON. */
	data_json?: string | null,
};

/**  Theme origin: prebuilt (immutable) or custom (user-added). */
export type ThemeOrigin = "prebuilt" | "custom";

/**
 *  Read model for a theme. Wraps the loaded `Theme` and serializes transparently
 *  (same `{ id, name, origin, data_json }` JSON the entity produced).
 */
export type ThemeView = Theme;

/**  Flat read model for a workspace row. Serializes to the SDK `Workspace` wire shape. */
export type WorkspaceView = {
	id: string,
	name: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

