//! The tauri transport layer. The orchestrator core (`app/` command/query structs
//! and the `Bus`) is transport-agnostic; this layer owns everything tauri-specific:
//! the per-surface output sink (`sink`) that bridges runtime output to the renderer
//! over `ipc::Channel`, the declarative shim macros (`macros`), and the macro-generated
//! domain command/query shims (`domain`).
//!
//! A shim builds the core command/query value, dispatches it through the managed
//! [`Bus`], and maps `shared::Error` to a wire string. The mechanical domain shims are
//! generated by the `transport_command!`/`transport_query!`/`transport_create!` macros
//! and registered (alongside the hand-written host/shell and transport-resident shims)
//! through `collect_transport!`. Tauri keeps per-command ACL and argument typing; the
//! wire (command name, argument shape, response JSON, error string) is unchanged.

pub mod domain;
pub mod macros;
pub mod sink;

/// The managed bus the shims dispatch through. The core is transport-agnostic; this
/// alias binds it to the desktop `Ctx` so the macros need no orchestrator import.
pub type Bus = orchestrator::shared::Bus<orchestrator::Ctx>;
